from colorama import Fore
import re

# TEXT OPTIONS
MAIN_CONSOLE_PREFIX = f"{Fore.BLUE}Ageis CIQ:{Fore.RESET} "
MAIN_CONSOLE_PREFIX_WARN = f"{Fore.YELLOW}Ageis CIQ:{Fore.RESET} "
WORKOUT_CONSOLE_PREFIX = f"{Fore.MAGENTA}WOC Console:{Fore.RESET} "
RATIONS_CONSOLE_PREFIX = f"{Fore.MAGENTA}RC Console:{Fore.RESET} "
HEALTH_CONSOLE_PREFIX = f"{Fore.MAGENTA}HC Console:{Fore.RESET} "
USER_PREFIX = f"{Fore.GREEN}You:{Fore.RESET} "

# LOGO OPTIONS
LOGO_BORDER_COLOR = Fore.BLUE
LOGO_TEXT_COLOR = Fore.RED
TITLE_COLOR = Fore.GREEN

# OS OPTIONS
TYPING_DELAY = 0.015
ANSI_ESCAPE_PATTERN = re.compile(r'(\033\[[0-9;]*m)')
OUTPUT_DIRECTORY_PATH = "output"
REPORT_FILE_NAME = "report.txt"

# NUMERIC OPTIONS
MAX_WEIGHT = 160
